/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
	export interface GlobalComponents {
		AButton: (typeof import('ant-design-vue/es'))['Button']
		ACol: (typeof import('ant-design-vue/es'))['Col']
		AForm: (typeof import('ant-design-vue/es'))['Form']
		AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
		AInput: (typeof import('ant-design-vue/es'))['Input']
		AInputPassword: (typeof import('ant-design-vue/es'))['InputPassword']
		AMenu: (typeof import('ant-design-vue/es'))['Menu']
		AMenuItem: (typeof import('ant-design-vue/es'))['MenuItem']
		AMenuItemGroup: (typeof import('ant-design-vue/es'))['MenuItemGroup']
		ARow: (typeof import('ant-design-vue/es'))['Row']
		ASpin: (typeof import('ant-design-vue/es'))['Spin']
		ASubMenu: (typeof import('ant-design-vue/es'))['SubMenu']
		Form: (typeof import('./src/components/atom/form/index.vue'))['default']
		FormItem: (typeof import('./src/components/atom/form/components/formItem.vue'))['default']
		Icon: (typeof import('./src/components/atom/icon/index.vue'))['default']
		RouterLink: (typeof import('vue-router'))['RouterLink']
		RouterView: (typeof import('vue-router'))['RouterView']
		SvgIcon: (typeof import('./src/components/atom/svgIcon/index.vue'))['default']
		Table: (typeof import('./src/components/atom/table/index.vue'))['default']
	}
}
